---
- name: Install Docker and Docker Compose on EC2
  hosts: all
  become: yes
  gather_facts: False
  tasks:
    - name: Install Docker
      apt:
        name:
          - docker.io  
          - python3
          - python3-pip
        update_cache: yes
        state: present

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-{{ lookup('pipe','uname -m') }}
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: Install Docker Python Module
      pip:
        name:
          - docker
          - docker-compose

    - name: Run Docker
      systemd:
        name: docker
        state: started